######################################################################
# Automatically generated by qmake (3.1) Sat Jun 2 12:51:49 2018
######################################################################

TEMPLATE = app
TARGET = gene_pathway_enrichment
INCLUDEPATH += .
QMAKE_CXXFLAGS += -frounding-math \
    -O3
QT += core \
    gui \
    xml \
    network \
    opengl
Qt +=  widgets
LIBS += -L/usr/local/lib/
LIBS += -lgsl \
    -lgslcblas \
    -lfreetype \
    -lssl

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/annotation.h \
           src/annotationDialog.h \
           src/comparator.h \
           src/filedownloader.h \
           src/geneAnnotation.h \
           src/heatmap.h \
           src/KGML.h \
           src/mainwindow.h \
           src/pathviewer.h \
           src/pathviewer2.h \
           src/pathway.h \
           src/polyeder.h \
           src/stick.h \
           src/testpathway.h \
           src/tokenSeparator.h \
           src/trackball.h \
           src/trackMover.h \
           src/basicMath/algebraBasic.h \
           src/basicMath/eigenValueDecomposition.h \
           src/basicMath/funcFit.h \
           src/basicMath/geomBasic.h \
           src/basicMath/initialTensor.h \
           src/basicMath/linreg.h \
           src/basicMath/Math.h \
           src/basicMath/matrix.h \
           src/basicMath/normalPDF.h \
           src/basicMath/statistics.h \
           src/basicMath/svd.h \
           src/forceDirectedLayout/graph.h \
           src/forceDirectedLayout/layout.h
SOURCES += src/annotation.cpp \
           src/annotationDialog.cpp \
           src/filedownloader.cpp \
           src/geneAnnotation.cpp \
           src/heatmap.cpp \
           src/KGML.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/pathviewer.cpp \
           src/pathviewer2.cpp \
           src/pathway.cpp \
           src/polyeder.cpp \
           src/stick.cpp \
           src/testpathway.cpp \
           src/tokenSeparator.cpp \
           src/trackball.cpp \
           src/trackMover.cpp \
           src/basicMath/algebraBasic.cpp \
           src/basicMath/eigenValueDecomposition.cpp \
           src/basicMath/geomBasic.cpp \
           src/basicMath/initialTensor.cpp \
           src/basicMath/matrix.cpp \
           src/basicMath/normalPDF.cpp \
           src/basicMath/statistics.cpp \
           src/basicMath/svd.cpp \
           src/forceDirectedLayout/graph.cpp \
           src/forceDirectedLayout/layout.cpp
